services:
  backend:
    build:
      context: ./src/OmniCatalogue.Backend
    ports:
      - "5106:5106"
    environment:
      - ASPNETCORE_URLS=http://+:5106
    networks:
      - omnicatalogue-net

  frontend:
    build:
      context: ./src/OmniCatalogue.Frontend
    ports:
      - "5173:80"
    networks:
      - omnicatalogue-net
    environment:
      - VITE_BACKEND_URL=http://localhost:5106

networks:
  omnicatalogue-net:
    driver: bridge
