name: Main Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build-test-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Frontend Dependencies
        working-directory: ./src/OmniCatalogue.Frontend
        run: npm install

      - name: Build Frontend
        working-directory: ./src/OmniCatalogue.Frontend
        run: npm run build

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Install Backend Dependencies
        working-directory: ./src/OmniCatalogue.Backend
        run: dotnet restore

      - name: Build Backend
        working-directory: ./src/OmniCatalogue.Backend
        run: dotnet build --configuration Release

  snyk-scan:
    runs-on: ubuntu-latest
    needs: build-test-lint

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Snyk Test Frontend
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: code test
        continue-on-error: true

      - name: Snyk Test Backend
        uses: snyk/actions/dotnet@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: code test
        continue-on-error: true

  docker-build-and-push:
    runs-on: ubuntu-latest
    needs: [build-test-lint, snyk-scan]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Frontend Image
        run: |
          docker build -t ghcr.io/${{ github.repository }}/omnicatalogue-frontend:latest -f src/OmniCatalogue.Frontend/Dockerfile .
          docker push ghcr.io/${{ github.repository }}/omnicatalogue-frontend:latest

      - name: Build and Push Backend Image
        run: |
          docker build -t ghcr.io/${{ github.repository }}/omnicatalogue-backend:latest -f src/OmniCatalogue.Backend/Dockerfile .
          docker push ghcr.io/${{ github.repository }}/omnicatalogue-backend:latest
